name: Generate RSS Feed for CCSU News

on:
  schedule:
    # Runs every day at 00:00 UTC (5:30 AM IST).
    # You can adjust this cron schedule as needed.
    # Example: "0 */6 * * *" for every 6 hours
    - cron: '*/30 * * * *' 
  workflow_dispatch: # Allows manual triggering from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out your repository code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use the latest Python 3 version

      - name: Install dependencies
        run: pip install -r requirements.txt # Installs requests, beautifulsoup4, lxml

      - name: Run Scraper and Generate RSS
        run: python scripts/ccsu_scraper.py # Executes your Python script

      - name: Commit and Push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ccsu_news_feed.xml # Add the generated RSS file
          git diff --quiet --exit-code || git commit -m "Automated RSS feed update"
          git push
        env:
          # Use the default GITHUB_TOKEN for pushing changes
          GITHUB_TOKEN: ${{ secrets.GITHUB_T
          OKEN }}
