name: Generate RSS Feed

on:
  schedule:
    # Runs every 30 minutes.
    # The '*/30' in the minute field means "every 30th minute".
    # The '*' in the hour, day of month, month, and day of week fields
    # means "every hour", "every day of the month", "every month", and "every day of the week".
    # So, this translates to "at minute 0 and minute 30 of every hour, every day."
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run Scraper and Generate RSS
        run: python scripts/ccsu_scraper.py

      - name: Commit and Push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ccsu_news_feed.xml
          git diff --quiet --exit-code || git commit -m "Automated RSS feed update"
          git push           
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
