name: Update RSS Feed

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 feedgen

      - name: Run Script
        run: python generate_rss.py

      - name: Commit and Push
        env:
          REPO_URL: https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ccs-feed.xml
          git diff --cached --quiet || git commit -m "Auto update RSS feed"
          git push "$REPO_URL" HEAD:main
